{
 "title": "Imported Giacomo Exploration",
 "time": { "from": "2015-12-28T00:00:00.000Z", "to": "2016-01-11T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "wind_turbine",
    "query": "{\"find\": \"terms\", \"field\": \"wind_turbine\"}"
   },
   {
    "name": "start_timestamp",
    "query": "{\"find\": \"terms\", \"field\": \"timestamp\", \"query\":\"timestamp:[2016-01-01T00:00:00 TO *]\"}"
   },
   {
    "name": "end_timestamp",
    "query": "{\"find\": \"terms\", \"field\": \"timestamp\", \"query\":\"timestamp:[2016-01-08T00:00:00 TO *]\"}"
   },
   {
    "name": "last_week_timestamp",
    "query": "{\"find\": \"terms\", \"field\": \"timestamp\", \"query\":\"timestamp:[2015-12-25T00:00:00 TO *]\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of unavailable turbines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Faulty",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "IsFaulty",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "IsFaulty:1",
     "timeField": "timestamp"
    },
    {
     "alias": "Annual Service",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "ActionsPerformed:\"Annual Service\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Currently Faulty",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "IsFaulty",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "IsFaulty:1",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Nacelle Direction vs Wind Speed",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Nac_Direction_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Amb_WindSpeed_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total SOK Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "KPIS_10MIN-SOKTIME",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Currently in Annual Service",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "IsFaulty",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "ActionsPerformed:\"Annual Service\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "wind speed (m/s)" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Amb_WindSpeed_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {
        "minimize": false,
        "model": "simple",
        "window": 20
       },
       "type": "moving_avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ActivePower_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ActivePower_Avg-SQL-10minAvg",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "wind_turbine:$wind_turbine",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Power Curve evolution (last two weeks)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ActivePower_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine AND IsFaulty:0 AND (NOT ActionsPerformed:\"Annual Service\") AND timestamp:[$last_week_timestamp TO $end_timestamp]",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Amb_WindSpeed_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine AND IsFaulty:0 AND (NOT ActionsPerformed:\"Annual Service\") AND timestamp:[$last_week_timestamp TO $end_timestamp]",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "timestamp",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine AND IsFaulty:0 AND (NOT ActionsPerformed:\"Annual Service\") AND timestamp:[$last_week_timestamp TO $end_timestamp]",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Power Curve (last 7 days)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ActivePower_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine AND IsFaulty:0 AND (NOT ActionsPerformed:\"Annual Service\") AND timestamp:[$start_timestamp TO $end_timestamp]",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Amb_WindSpeed_Avg-SQL-10minAvg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "wind_turbine:$wind_turbine AND IsFaulty:0 AND (NOT ActionsPerformed:\"Annual Service\") AND timestamp:[$start_timestamp TO $end_timestamp]",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}