"""empty message

Revision ID: 36ec82ca4640
Revises: 214bd7df1836
Create Date: 2018-05-14 16:58:27.464729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36ec82ca4640'
down_revision = '214bd7df1836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_task', 'detection_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_task', sa.Column('detection_request', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
