"""empty message

Revision ID: 72afd73676f7
Revises: a8eff9b4eb8c
Create Date: 2018-05-16 10:42:14.597097

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72afd73676f7'
down_revision = 'a8eff9b4eb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_task', sa.Column('task_code', sa.String(length=60), nullable=True))
    op.alter_column('detection_task', 'configuration_id', existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f('ix_detection_task_task_code'), 'detection_task', ['task_code'], unique=True)
    op.create_index(op.f('ix_detection_task_upload_code'), 'detection_task', ['upload_code'], unique=False)
    op.drop_constraint('detection_task_upload_code_key', 'detection_task', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('detection_task_upload_code_key', 'detection_task', ['upload_code'])
    op.drop_index(op.f('ix_detection_task_upload_code'), table_name='detection_task')
    op.drop_index(op.f('ix_detection_task_task_code'), table_name='detection_task')
    op.alter_column('detection_task', 'configuration_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_column('detection_task', 'task_code')
    # ### end Alembic commands ###
