"""empty message

Revision ID: d150ec910552
Revises: 0a0b71a292d7
Create Date: 2018-06-07 11:25:28.189427

"""
import os
import shutil

from alembic import op
import sqlalchemy as sa

from config import UPLOAD_ROOT_FOLDER


# revision identifiers, used by Alembic.
revision = 'd150ec910552'
down_revision = '0a0b71a292d7'
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()

    # move the files from their old location to the new one
    result = connection.execute("""
    SELECT location, company_id, filename 
      FROM data_source 
      WHERE location IS NOT NULL;
    """)


    for row in result.fetchall():
        row_as_dict = dict(row)
        old_location = row_as_dict['location']
        company_id = row_as_dict['company_id']
        filename = row_as_dict['filename']

        new_path = os.path.join(UPLOAD_ROOT_FOLDER, str(company_id))
        os.makedirs(new_path, exist_ok=True)
        new_location = os.path.join(new_path, filename)

        shutil.move(old_location, new_location)

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_source', 'datasource_configuration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_data_source_location', table_name='data_source')
    op.drop_column('data_source', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_data_source_location', 'data_source', ['location'], unique=False)
    op.alter_column('data_source', 'datasource_configuration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
