"""empty message

Revision ID: 427bda85b612
Revises: da583005adb5
Create Date: 2018-09-03 13:09:15.195808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427bda85b612'
down_revision = 'da583005adb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turbinehealth', sa.Column('availability', sa.Float(), nullable=True))
    op.add_column('turbinehealth', sa.Column('efficiency', sa.Float(), nullable=True))
    op.add_column('turbinehealth', sa.Column('estimated_cost_of_repair', sa.DECIMAL(), nullable=True))
    op.add_column('turbinehealth', sa.Column('estimated_residual_time', sa.Integer(), nullable=True))
    op.add_column('turbinehealth', sa.Column('time_between_failures', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turbinehealth', 'time_between_failures')
    op.drop_column('turbinehealth', 'estimated_residual_time')
    op.drop_column('turbinehealth', 'estimated_cost_of_repair')
    op.drop_column('turbinehealth', 'efficiency')
    op.drop_column('turbinehealth', 'availability')
    # ### end Alembic commands ###
