"""empty message

Revision ID: 76f9b748967b
Revises: d150ec910552
Create Date: 2018-06-07 16:02:17.640076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f9b748967b'
down_revision = 'd150ec910552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_source', 'datasource_configuration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('detection_task', sa.Column('training_task_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'detection_task', 'training_task', ['training_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_task', type_='foreignkey')
    op.drop_column('detection_task', 'training_task_id')
    op.alter_column('data_source', 'datasource_configuration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
