"""empty message

Revision ID: 2279b76102e0
Revises: 72afd73676f7
Create Date: 2018-05-16 11:16:13.569457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2279b76102e0'
down_revision = '72afd73676f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_result', sa.Column('task_code', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_detection_result_task_code'), 'detection_result', ['task_code'], unique=True)
    op.create_index(op.f('ix_detection_result_upload_code'), 'detection_result', ['upload_code'], unique=False)
    op.drop_constraint('detection_result_upload_code_key', 'detection_result', type_='unique')
    op.alter_column('detection_task', 'task_code', existing_type=sa.VARCHAR(length=60), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_task', 'task_code', existing_type=sa.VARCHAR(length=60), nullable=True)
    op.create_unique_constraint('detection_result_upload_code_key', 'detection_result', ['upload_code'])
    op.drop_index(op.f('ix_detection_result_upload_code'), table_name='detection_result')
    op.drop_index(op.f('ix_detection_result_task_code'), table_name='detection_result')
    op.drop_column('detection_result', 'task_code')
    # ### end Alembic commands ###
