"""empty message

Revision ID: c41e505e8507
Revises: 7ce46b15179f
Create Date: 2018-08-23 17:17:07.848139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41e505e8507'
down_revision = '7ce46b15179f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('turbine_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=250), nullable=False),
    sa.Column('value', sa.Float(precision=53), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_prediction_id', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthscore_created_at'), 'healthscore', ['created_at'], unique=False)
    op.create_index(op.f('ix_healthscore_last_update'), 'healthscore', ['last_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthscore_last_update'), table_name='healthscore')
    op.drop_index(op.f('ix_healthscore_created_at'), table_name='healthscore')
    op.drop_table('healthscore')
    # ### end Alembic commands ###
