"""empty message

Revision ID: 7044412b9b93
Revises: 0038de4762fe
Create Date: 2018-09-19 17:22:11.078220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7044412b9b93'
down_revision = '0038de4762fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variablehealth')
    op.add_column('turbinehealth', sa.Column('healthscore', sa.DECIMAL()))
    op.execute("Update turbinehealth set healthscore = 0")
    op.alter_column('turbinehealth', 'healthscore', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turbinehealth', 'healthscore')
    op.create_table('variablehealth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('group_variable_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group_variable_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['componenthealth.id'], name='variablehealth_component_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='variablehealth_pkey')
    )
    # ### end Alembic commands ###
