"""add meta json column to data_source

Revision ID: 214bd7df1836
Revises: 436de06a28b1
Create Date: 2018-05-11 12:13:48.822768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214bd7df1836'
down_revision = '436de06a28b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'meta')
    # ### end Alembic commands ###
