"""empty message

Revision ID: 436de06a28b1
Revises: 
Create Date: 2018-05-10 17:29:59.495451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436de06a28b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_created_at'), 'company', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_last_update'), 'company', ['last_update'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Enum('USER', 'ADMIN', name='userpermissions'), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_last_update'), 'user', ['last_update'], unique=False)
    op.create_table('company_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_configuration_created_at'), 'company_configuration', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_configuration_last_update'), 'company_configuration', ['last_update'], unique=False)
    op.create_table('customer_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('FILE_UPLOAD', 'DETECTION_STARTED', 'CONFIGURATION_UPDATE', name='actions'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_action_created_at'), 'customer_action', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_action_last_update'), 'customer_action', ['last_update'], unique=False)
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('upload_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('FILESYSTEM', 'BLOBSTORE', name='uploadtypes'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_created_at'), 'data_source', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_source_last_update'), 'data_source', ['last_update'], unique=False)
    op.create_index(op.f('ix_data_source_location'), 'data_source', ['location'], unique=False)
    op.create_index(op.f('ix_data_source_name'), 'data_source', ['name'], unique=True)
    op.create_index(op.f('ix_data_source_type'), 'data_source', ['type'], unique=False)
    op.create_index(op.f('ix_data_source_upload_code'), 'data_source', ['upload_code'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_created_at'), 'user_profile', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profile_last_update'), 'user_profile', ['last_update'], unique=False)
    op.create_table('detection_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(length=60), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('detection_request', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_code')
    )
    op.create_index(op.f('ix_detection_task_created_at'), 'detection_task', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_task_last_update'), 'detection_task', ['last_update'], unique=False)
    op.create_table('detection_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(length=60), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('detection_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['detection_task_id'], ['detection_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_code')
    )
    op.create_index(op.f('ix_detection_result_created_at'), 'detection_result', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_result_last_update'), 'detection_result', ['last_update'], unique=False)
    op.create_table('detection_task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detection_task_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['detection_task_id'], ['detection_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_task_status_created_at'), 'detection_task_status', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_task_status_last_update'), 'detection_task_status', ['last_update'], unique=False)
    op.create_index(op.f('ix_detection_task_status_state'), 'detection_task_status', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_task_status_state'), table_name='detection_task_status')
    op.drop_index(op.f('ix_detection_task_status_last_update'), table_name='detection_task_status')
    op.drop_index(op.f('ix_detection_task_status_created_at'), table_name='detection_task_status')
    op.drop_table('detection_task_status')
    op.drop_index(op.f('ix_detection_result_last_update'), table_name='detection_result')
    op.drop_index(op.f('ix_detection_result_created_at'), table_name='detection_result')
    op.drop_table('detection_result')
    op.drop_index(op.f('ix_detection_task_last_update'), table_name='detection_task')
    op.drop_index(op.f('ix_detection_task_created_at'), table_name='detection_task')
    op.drop_table('detection_task')
    op.drop_index(op.f('ix_user_profile_last_update'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_created_at'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_data_source_upload_code'), table_name='data_source')
    op.drop_index(op.f('ix_data_source_type'), table_name='data_source')
    op.drop_index(op.f('ix_data_source_name'), table_name='data_source')
    op.drop_index(op.f('ix_data_source_location'), table_name='data_source')
    op.drop_index(op.f('ix_data_source_last_update'), table_name='data_source')
    op.drop_index(op.f('ix_data_source_created_at'), table_name='data_source')
    op.drop_table('data_source')
    op.drop_index(op.f('ix_customer_action_last_update'), table_name='customer_action')
    op.drop_index(op.f('ix_customer_action_created_at'), table_name='customer_action')
    op.drop_table('customer_action')
    op.drop_index(op.f('ix_company_configuration_last_update'), table_name='company_configuration')
    op.drop_index(op.f('ix_company_configuration_created_at'), table_name='company_configuration')
    op.drop_table('company_configuration')
    op.drop_index(op.f('ix_user_last_update'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_company_last_update'), table_name='company')
    op.drop_index(op.f('ix_company_created_at'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
