"""empty message

Revision ID: 64ebdc56387f
Revises: 76f9b748967b
Create Date: 2018-06-08 15:39:11.532212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ebdc56387f'
down_revision = '76f9b748967b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_task', sa.Column('parent_training_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training_task', 'training_task', ['parent_training_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_task', type_='foreignkey')
    op.drop_column('training_task', 'parent_training_id')
    # ### end Alembic commands ###
