"""empty message

Revision ID: 984d3ae7ebee
Revises: c41e505e8507
Create Date: 2018-08-31 19:12:31.678829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984d3ae7ebee'
down_revision = 'c41e505e8507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('turbine', sa.String(length=25), nullable=False),
    sa.Column('component', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_component'), 'maintenance', ['component'], unique=False)
    op.create_index(op.f('ix_maintenance_created_at'), 'maintenance', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenance_end_date'), 'maintenance', ['end_date'], unique=False)
    op.create_index(op.f('ix_maintenance_last_update'), 'maintenance', ['last_update'], unique=False)
    op.create_index(op.f('ix_maintenance_start_date'), 'maintenance', ['start_date'], unique=False)
    op.create_index(op.f('ix_maintenance_turbine'), 'maintenance', ['turbine'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_turbine'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_start_date'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_last_update'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_end_date'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_created_at'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_component'), table_name='maintenance')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
