"""empty message

Revision ID: a8eff9b4eb8c
Revises: 776de775357e
Create Date: 2018-05-15 15:48:52.797846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8eff9b4eb8c'
down_revision = '776de775357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_task', sa.Column('configuration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detection_task', 'company_configuration', ['configuration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_task', type_='foreignkey')
    op.drop_column('detection_task', 'configuration_id')
    # ### end Alembic commands ###
