"""empty message

Revision ID: ebd1bfd7db14
Revises: 3ca3acdeef5d
Create Date: 2018-06-04 15:58:49.357586

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

revision = 'ebd1bfd7db14'
down_revision = '3ca3acdeef5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    labeltypes = ENUM('NORMAL', 'ABNORMAL', name='labeltypes', create_type=False)
    labeltypes.create(op.get_bind(), checkfirst=True)
    op.create_table('data_source_configuration',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('meta', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='data_source_company_id_fk'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_data_source_configuration_created_at'), 'data_source_configuration', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_data_source_configuration_last_update'), 'data_source_configuration', ['last_update'],
                    unique=False)
    op.create_index(op.f('ix_data_source_configuration_name'), 'data_source_configuration', ['name'], unique=True)
    op.create_table('training_task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('datasource_configuration_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=60), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('company_configuration_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('task_code', sa.String(length=60), nullable=False),
                    sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(['company_configuration_id'], ['company_configuration.id'], ),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.ForeignKeyConstraint(['datasource_configuration_id'], ['data_source_configuration.id'],
                                            name='training_task_datasource_configuration_id_fk'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_training_task_created_at'), 'training_task', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_task_last_update'), 'training_task', ['last_update'], unique=False)
    op.create_index(op.f('ix_training_task_name'), 'training_task', ['name'], unique=True)
    op.create_index(op.f('ix_training_task_task_code'), 'training_task', ['task_code'], unique=True)
    op.create_table('datasources_to_training_task',
                    sa.Column('training_task_id', sa.Integer(), nullable=True),
                    sa.Column('data_source_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
                    sa.ForeignKeyConstraint(['training_task_id'], ['training_task.id'], )
                    )
    op.create_table('training_task_status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('training_task_id', sa.Integer(), nullable=False),
                    sa.Column('state', sa.String(), nullable=True),
                    sa.Column('message', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['training_task_id'], ['training_task.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_training_task_status_created_at'), 'training_task_status', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_task_status_last_update'), 'training_task_status', ['last_update'], unique=False)
    op.create_index(op.f('ix_training_task_status_state'), 'training_task_status', ['state'], unique=False)
    op.add_column('data_source', sa.Column('datasource_configuration_id', sa.Integer(), nullable=True))
    op.add_column('data_source', sa.Column('label', labeltypes, nullable=True))
    op.create_index(op.f('ix_data_source_label'), 'data_source', ['label'], unique=False)
    op.create_foreign_key('data_source_datasource_configuration_id_fkey', 'data_source', 'data_source_configuration',
                          ['datasource_configuration_id'], ['id'])

    # ### end Alembic commands ###
    op.create_unique_constraint('_datasource_company_id_name_uc', 'data_source', ['company_id', 'name'])
    op.drop_index('ix_data_source_name', table_name='data_source')
    op.create_index(op.f('ix_data_source_name'), 'data_source', ['name'], unique=False)
    op.create_unique_constraint('_datasource_config_name_company_uc', 'data_source_configuration',
                                ['company_id', 'name'])
    op.drop_index('ix_data_source_configuration_name', table_name='data_source_configuration')
    op.create_index(op.f('ix_data_source_configuration_name'), 'data_source_configuration', ['name'], unique=False)


def downgrade():
    op.drop_index(op.f('ix_data_source_configuration_name'), table_name='data_source_configuration')
    op.create_index('ix_data_source_configuration_name', 'data_source_configuration', ['name'], unique=True)
    op.drop_constraint('_datasource_config_name_company_uc', 'data_source_configuration', type_='unique')
    op.drop_index(op.f('ix_data_source_name'), table_name='data_source')
    op.create_index('ix_data_source_name', 'data_source', ['name'], unique=True)
    op.drop_constraint('_datasource_company_id_name_uc', 'data_source', type_='unique')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_source_datasource_configuration_id_fkey', 'data_source', type_='foreignkey')
    op.drop_index(op.f('ix_data_source_label'), table_name='data_source')
    op.drop_column('data_source', 'label')
    op.drop_column('data_source', 'datasource_configuration_id')
    op.drop_index(op.f('ix_training_task_status_state'), table_name='training_task_status')
    op.drop_index(op.f('ix_training_task_status_last_update'), table_name='training_task_status')
    op.drop_index(op.f('ix_training_task_status_created_at'), table_name='training_task_status')
    op.drop_table('training_task_status')
    op.drop_table('datasources_to_training_task')
    op.drop_index(op.f('ix_training_task_task_code'), table_name='training_task')
    op.drop_index(op.f('ix_training_task_name'), table_name='training_task')
    op.drop_index(op.f('ix_training_task_last_update'), table_name='training_task')
    op.drop_index(op.f('ix_training_task_created_at'), table_name='training_task')
    op.drop_table('training_task')
    op.drop_index(op.f('ix_data_source_configuration_name'), table_name='data_source_configuration')
    op.drop_index(op.f('ix_data_source_configuration_last_update'), table_name='data_source_configuration')
    op.drop_index(op.f('ix_data_source_configuration_created_at'), table_name='data_source_configuration')
    op.drop_table('data_source_configuration')
    # ### end Alembic commands ###
