"""empty message

Revision ID: 37ddc9df2f9f
Revises: 427bda85b612
Create Date: 2018-09-03 15:01:22.664184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ddc9df2f9f'
down_revision = '427bda85b612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('turbine_id', sa.Integer(), nullable=True))
    op.drop_column('alerts', 'turbine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('turbine', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'turbine_id')
    # ### end Alembic commands ###
