"""empty message

Revision ID: 9265739eb1bd
Revises: 37ddc9df2f9f
Create Date: 2018-09-04 11:51:17.775604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9265739eb1bd'
down_revision = '37ddc9df2f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turbinehealth', sa.Column('downtime', sa.Float(), nullable=True))
    op.add_column('turbinehealth', sa.Column('failure_cost', sa.DECIMAL(), nullable=True))
    op.add_column('turbinehealth', sa.Column('revenue_loss', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turbinehealth', 'revenue_loss')
    op.drop_column('turbinehealth', 'failure_cost')
    op.drop_column('turbinehealth', 'downtime')
    # ### end Alembic commands ###
