"""empty message

Revision ID: 3ca3acdeef5d
Revises: 4df6eeb7edba
Create Date: 2018-05-29 16:22:03.851574

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ca3acdeef5d'
down_revision = '4df6eeb7edba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('diagnostic_task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('detection_task_id', sa.Integer(), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=True),
                    sa.Column('datasource_id', sa.Integer(), nullable=True),
                    sa.Column('upload_code', sa.String(length=60), nullable=False),
                    sa.Column('task_code', sa.String(length=60), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.ForeignKeyConstraint(['datasource_id'], ['data_source.id'], ),
                    sa.ForeignKeyConstraint(['detection_task_id'], ['detection_task.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_diagnostic_task_created_at'), 'diagnostic_task', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnostic_task_last_update'), 'diagnostic_task', ['last_update'], unique=False)
    op.create_index(op.f('ix_diagnostic_task_task_code'), 'diagnostic_task', ['task_code'], unique=False)
    op.create_index(op.f('ix_diagnostic_task_upload_code'), 'diagnostic_task', ['upload_code'], unique=False)
    op.create_table('diagnostic_task_status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('diagnostic_task_id', sa.Integer(), nullable=False),
                    sa.Column('state', sa.String(), nullable=True),
                    sa.Column('message', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['diagnostic_task_id'], ['diagnostic_task.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_diagnostic_task_status_created_at'), 'diagnostic_task_status', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_diagnostic_task_status_last_update'), 'diagnostic_task_status', ['last_update'],
                    unique=False)
    op.create_index(op.f('ix_diagnostic_task_status_state'), 'diagnostic_task_status', ['state'], unique=False)
    op.create_table('diagnostic_result',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('upload_code', sa.String(length=60), nullable=True),
                    sa.Column('task_code', sa.String(length=60), nullable=True),
                    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('diagnostic_task_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.ForeignKeyConstraint(['diagnostic_task_id'], ['diagnostic_task.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_diagnostic_result_created_at'), 'diagnostic_result', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnostic_result_last_update'), 'diagnostic_result', ['last_update'], unique=False)
    op.create_index(op.f('ix_diagnostic_result_task_code'), 'diagnostic_result', ['task_code'], unique=True)
    op.create_index(op.f('ix_diagnostic_result_upload_code'), 'diagnostic_result', ['upload_code'], unique=False)
    op.alter_column('detection_task', 'task_code',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_task', 'task_code',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=True)
    op.drop_index(op.f('ix_diagnostic_task_status_state'), table_name='diagnostic_task_status')
    op.drop_index(op.f('ix_diagnostic_task_status_last_update'), table_name='diagnostic_task_status')
    op.drop_index(op.f('ix_diagnostic_task_status_created_at'), table_name='diagnostic_task_status')
    op.drop_table('diagnostic_task_status')
    op.drop_index(op.f('ix_diagnostic_task_upload_code'), table_name='diagnostic_task')
    op.drop_index(op.f('ix_diagnostic_task_task_code'), table_name='diagnostic_task')
    op.drop_index(op.f('ix_diagnostic_task_last_update'), table_name='diagnostic_task')
    op.drop_index(op.f('ix_diagnostic_task_created_at'), table_name='diagnostic_task')
    op.drop_table('diagnostic_task')
    op.drop_index(op.f('ix_diagnostic_result_upload_code'), table_name='diagnostic_result')
    op.drop_index(op.f('ix_diagnostic_result_task_code'), table_name='diagnostic_result')
    op.drop_index(op.f('ix_diagnostic_result_last_update'), table_name='diagnostic_result')
    op.drop_index(op.f('ix_diagnostic_result_created_at'), table_name='diagnostic_result')
    op.drop_table('diagnostic_result')
    # ### end Alembic commands ###
