"""empty message

Revision ID: da583005adb5
Revises: 0a43812596b0
Create Date: 2018-09-01 18:29:36.502241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da583005adb5'
down_revision = '0a43812596b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('windfarmhealth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_windfarmhealth_created_at'), 'windfarmhealth', ['created_at'], unique=False)
    op.create_index(op.f('ix_windfarmhealth_last_update'), 'windfarmhealth', ['last_update'], unique=False)
    op.add_column('turbinehealth', sa.Column('windfarm_health_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'turbinehealth', 'windfarmhealth', ['windfarm_health_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turbinehealth', type_='foreignkey')
    op.drop_column('turbinehealth', 'windfarm_health_id')
    op.drop_index(op.f('ix_windfarmhealth_last_update'), table_name='windfarmhealth')
    op.drop_index(op.f('ix_windfarmhealth_created_at'), table_name='windfarmhealth')
    op.drop_table('windfarmhealth')
    # ### end Alembic commands ###
