"""empty message

Revision ID: 665ca9748b1b
Revises: 64ebdc56387f
Create Date: 2018-07-23 11:26:18.743787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665ca9748b1b'
down_revision = '64ebdc56387f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('TRAINING', 'DETECTION', 'DIAGNOSTIC', name='tasktypes'), nullable=True),
    sa.Column('task_code', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_last_update'), 'task', ['last_update'], unique=False)
    op.create_index(op.f('ix_task_task_code'), 'task', ['task_code'], unique=False)
    op.create_index(op.f('ix_task_type'), 'task', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_type'), table_name='task')
    op.drop_index(op.f('ix_task_task_code'), table_name='task')
    op.drop_index(op.f('ix_task_last_update'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
