"""empty message

Revision ID: 0a43812596b0
Revises: daa6a43fdf79
Create Date: 2018-09-01 16:50:33.609131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a43812596b0'
down_revision = 'daa6a43fdf79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turbinehealth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('turbine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turbinehealth_created_at'), 'turbinehealth', ['created_at'], unique=False)
    op.create_index(op.f('ix_turbinehealth_last_update'), 'turbinehealth', ['last_update'], unique=False)
    op.create_table('componenthealth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('parent_turbine_health_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['parent_turbine_health_id'], ['turbinehealth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_componenthealth_created_at'), 'componenthealth', ['created_at'], unique=False)
    op.create_index(op.f('ix_componenthealth_last_update'), 'componenthealth', ['last_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_componenthealth_last_update'), table_name='componenthealth')
    op.drop_index(op.f('ix_componenthealth_created_at'), table_name='componenthealth')
    op.drop_table('componenthealth')
    op.drop_index(op.f('ix_turbinehealth_last_update'), table_name='turbinehealth')
    op.drop_index(op.f('ix_turbinehealth_created_at'), table_name='turbinehealth')
    op.drop_table('turbinehealth')
    # ### end Alembic commands ###
